version: '3'

services:

  backevent:
    container_name: backevent
    build:
        context: ./backevent
    ports:
      - "1337:1337"
    volumes:
      - "./backevent/:/usr/src/app"
    command: sh -c "npm install --prune && npm start"

  frontevent:
    container_name: frontevent
    build:
      context: ./frontevent
    ports:
      - "4200:4200"
    volumes:
      - "./frontevent/:/usr/src/app"
    command: sh -c "npm install --prune && npm start"
