version: '3'

services:

  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  backevent:
    container_name: backevent
    build:
      context: ./backevent
    ports:
      - 1337:1337
    volumes:
      - ./backevent:/usr/src/app/
    command: sh -c "npm start"
    depends_on: [db]
    links:
      - db:database

  frontevent:
    container_name: frontevent
    build:
      context: ./frontevent
    ports:
      - 4200:4200
    volumes:
      - ./frontevent:/usr/src/app/
    command: sh -c "npm start"
    depends_on: [backevent]
    links:
      - backevent
