name: Test workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose build
      - name: Test backend
        run: docker-compose  run --rm backevent npm test
      # Skip because i want use flex layout but not adapted for angular 13 (v12 ok)
      #- name: Test frontend
      #  run: docker-compose  run --rm frontevent npm run test:git
