name: Test workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build container
        run: docker-compose build
      - name: Test backend
        run: docker-compose  run backevent npm test
      - name: Test frontend
        run: docker-compose  run frontevent npm run test:git
